vscode:
  extensions:
    - Pivotal.vscode-spring-boot@1.11.0:gKokcVIlbvXM5pr9HCsGiA==
    - vscjava.vscode-spring-initializr@0.4.6:WOgtgIwX3Ngy4pM9ArXjCQ==
    - vscjava.vscode-spring-boot-dashboard@0.1.6:/G6fobfzYSrYZdNU7UB78g==
